const types = {
  FETCH_USERS_ATTEMPT: 'FETCH_USERS_ATTEMPT',
  FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
  FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',

  POST_USER_ATTEMPT: 'POST_USER_ATTEMPT',
  POST_USER_SUCCESS: 'POST_USER_SUCCESS',
  POST_USER_FAILURE: 'POST_USER_FAILURE',

  ALTER_USER_ATTEMPT: 'ALTER_USER_ATTEMPT',
  ALTER_USER_SUCCESS: 'ALTER_USER_SUCCESS',
  ALTER_USER_FAILURE: 'ALTER_USER_FAILURE',
};

export default types;
