const types = {
  LOGIN_ATTEMPT: 'LOGIN_ATTEMPT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  LOGOUT_ATTEMPT: 'LOGOUT_ATTEMPT',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
};

export default types;
