const types = {
  FETCH_APPLICATIONS_ATTEMPT: 'FETCH_APPLICATIONS_ATTEMPT',
  FETCH_APPLICATIONS_SUCCESS: 'FETCH_APPLICATIONS_SUCCESS',
  FETCH_APPLICATIONS_FAILURE: 'FETCH_APPLICATIONS_FAILURE',

  POST_APPLICATION_ATTEMPT: 'POST_APPLICATION_ATTEMPT',
  POST_APPLICATION_SUCCESS: 'POST_APPLICATION_SUCCESS',
  POST_APPLICATION_FAILURE: 'POST_APPLICATION_FAILURE',

  DELETE_APPLICATION_ATTEMPT: 'DELETE_APPLICATION_ATTEMPT',
  DELETE_APPLICATION_SUCCESS: 'DELETE_APPLICATION_SUCCESS',
  DELETE_APPLICATION_FAILURE: 'DELETE_APPLICATION_FAILURE',
};

export default types;
