const types = {
  FETCH_APPLICATIONS_ATTEMPT: 'FETCH_APPLICATIONS_ATTEMPT',
  FETCH_APPLICATIONS_SUCCESS: 'FETCH_APPLICATIONS_SUCCESS',
  FETCH_APPLICATIONS_FAILURE: 'FETCH_APPLICATIONS_FAILURE',
};

export default types;
